https://www.dataquest.io/blog/numpy-cheat-sheet/

In [1]:
import numpy as np
a = [4,3,2,3]

### Importing/Exporting files 

In [2]:
filename = "D:/Python/Texts and docs/numpy/numpy.txt"
with open(filename, encoding='utf8') as infile:
    a = np.loadtxt(filename).astype('int')
    a = np.append(a,45)
a

array([ 23,   4,   3,   4,   5,  12,  56, 736, 736, 635,  53,  45,  45,
        45,  45])

In [3]:
with open(filename, encoding='utf8') as infile:
    from_csv = np.genfromtxt("D:/Python/Texts and docs/numpy/numpy.csv").astype('int')
    from_csv = np.append(from_csv,45)
print(from_csv)

[   3    3    4    5    3    4 1234    3  433   89   34   45   45   45]


In [4]:
# saving array in text and csv format.
np.savetxt("D:/Python/Texts and docs/numpy/numpy.txt",a,delimiter = ' ', fmt = "%d")
np.savetxt("D:/Python/Texts and docs/numpy/numpy.csv", from_csv, delimiter =',',fmt = "%d" )

### Creating arrays

In [5]:
create_array = np.array([2,1,2])
create_array

array([2, 1, 2])

In [6]:
create_arr_multi = np.array([(1,2,3),(1,2,34)])
create_arr_multi 

array([[ 1,  2,  3],
       [ 1,  2, 34]])

In [7]:
# zeros
print(np.zeros(3))
# ones
print("\n",np.ones((2,3)))

[0. 0. 0.]

 [[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 5x5array of 0 with 1 in diagonal
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
# array of 4 evenly divided values from 0 to 100
np.linspace(0,100,4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [10]:
# returns the step value in series range of between 0 to 10 (10 excluded)
np.arange(0,10,4)

array([0, 4, 8])

In [11]:
np.full((5,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [12]:
# random array of 4x5 matrix with 0 and 1
np.random.rand(4,5)

array([[0.86884927, 0.29572554, 0.84075092, 0.90577798, 0.30736461],
       [0.76925175, 0.39453163, 0.95033319, 0.97483474, 0.63627925],
       [0.06218624, 0.93092479, 0.36822438, 0.20145145, 0.85741484],
       [0.32126826, 0.30667297, 0.77116686, 0.11530778, 0.15371981]])

In [13]:
#random floats beetween 0 - 100 
(np.random.rand(4,5)*100)

array([[ 6.08580663,  3.93118596, 78.62229611, 42.45673276, 70.76151923],
       [63.79318563, 24.05055727, 65.6133571 , 17.97063347, 20.16246814],
       [43.14768396, 86.77238384, 64.92309847, 21.17505573, 67.23966283],
       [ 0.27202571, 27.77339713, 72.08794023, 79.07211796, 33.91871455]])

In [14]:
# returns random integer numbers from 0-5
arr = np.random.randint(5,size=(3,3))
arr

array([[1, 3, 1],
       [2, 2, 2],
       [3, 0, 1]])

### Inspecting properties

In [15]:
arr.size

9

In [16]:
arr.shape

(3, 3)

In [17]:
arr.dtype

dtype('int32')

In [18]:
arr.astype('float')

array([[1., 3., 1.],
       [2., 2., 2.],
       [3., 0., 1.]])

In [19]:
arr.tolist()

[[1, 3, 1], [2, 2, 2], [3, 0, 1]]

In [20]:
# viewing documentation
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

In [21]:
# copying, sorting or reshaping
cpy = np.copy(create_arr_multi)
cpy

array([[ 1,  2,  3],
       [ 1,  2, 34]])

In [22]:
cpy.view('int')

array([[ 1,  2,  3],
       [ 1,  2, 34]])

In [23]:
arr.sort(axis = 0)
arr

array([[1, 0, 1],
       [2, 2, 1],
       [3, 3, 2]])

In [24]:
flat = cpy.flatten()
flat

array([ 1,  2,  3,  1,  2, 34])

In [25]:
Transpose = arr.T
Transpose

array([[1, 2, 3],
       [0, 2, 3],
       [1, 1, 2]])

In [26]:
# try to flatten first and then resize
resize = flat.resize(2,3)
flat

array([[ 1,  2,  3],
       [ 1,  2, 34]])

In [27]:
reshape = np.reshape(flat, (3,2))
reshape

array([[ 1,  2],
       [ 3,  1],
       [ 2, 34]])

In [28]:
print(a)
np.append(a,342)

[ 23   4   3   4   5  12  56 736 736 635  53  45  45  45  45]


array([ 23,   4,   3,   4,   5,  12,  56, 736, 736, 635,  53,  45,  45,
        45,  45, 342])

In [29]:
delete = np.delete(a,-1)
delete

array([ 23,   4,   3,   4,   5,  12,  56, 736, 736, 635,  53,  45,  45,
        45])

In [30]:
print(reshape)
np.delete(reshape,0,1)

[[ 1  2]
 [ 3  1]
 [ 2 34]]


array([[ 2],
       [ 1],
       [34]])

In [31]:
np.delete(reshape,0,0)

array([[ 3,  1],
       [ 2, 34]])

### Combining and splitting

In [32]:
array1 = np.array([(2,1,33),(31,3,23)]).astype('int')
array2 = np.array([(3,23,8),(34,3,7)]).astype('int')
concat_row = np.concatenate((array1,array1))
concat_row

array([[ 2,  1, 33],
       [31,  3, 23],
       [ 2,  1, 33],
       [31,  3, 23]])

In [33]:
concat_col = np.concatenate((array1,array1), axis = 1)
concat_col

array([[ 2,  1, 33,  2,  1, 33],
       [31,  3, 23, 31,  3, 23]])

In [34]:
split_row = np.split(concat_row,4)
split_row

[array([[ 2,  1, 33]]),
 array([[31,  3, 23]]),
 array([[ 2,  1, 33]]),
 array([[31,  3, 23]])]

In [35]:
split_col = np.split(concat_col,2,axis = 1)
split_col

[array([[ 2,  1, 33],
        [31,  3, 23]]),
 array([[ 2,  1, 33],
        [31,  3, 23]])]

In [36]:
# horizontal split of each array element in 4th index
split_hcol = np.hsplit(concat_col,2)
split_hcol

[array([[ 2,  1, 33],
        [31,  3, 23]]),
 array([[ 2,  1, 33],
        [31,  3, 23]])]

### indexing slicing/ subsetting

In [37]:
# returns the index of the following row/col
print(concat_row)
concat_row[1,0]

[[ 2  1 33]
 [31  3 23]
 [ 2  1 33]
 [31  3 23]]


31

In [38]:
arr[0,2] = 22
arr

array([[ 1,  0, 22],
       [ 2,  2,  1],
       [ 3,  3,  2]])

In [39]:
# returns the array row wise from the given index of the column 
concat_row[0:4,1]

array([1, 3, 1, 3])

In [40]:
# returns all elements from indices (0,1)
concat_row[:2]

array([[ 2,  1, 33],
       [31,  3, 23]])

In [41]:
# returns all elemnets of that particular column 
concat_row[:,1]

array([1, 3, 1, 3])

In [42]:
# Returns all elements less than 3
concat_row<3

array([[ True,  True, False],
       [False, False, False],
       [ True,  True, False],
       [False, False, False]])

In [43]:
(concat_row<3) & (concat_row>21)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [44]:
bool_row = (concat_row<3) | (concat_row>21)
bool_row

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [45]:
print(concat_row)
inv_arr = ~bool_row
inv_arr

[[ 2  1 33]
 [31  3 23]
 [ 2  1 33]
 [31  3 23]]


array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False,  True, False]])

In [46]:
# Returns array that satisfies the condition e.g. arr[arr[<condition>]]
concat_row[(concat_row<3) | (concat_row>21)]

array([ 2,  1, 33, 31, 23,  2,  1, 33, 31, 23])

### Scalar Math

In [47]:
print(concat_row)
addition = np.add(concat_row,2)
addition

[[ 2  1 33]
 [31  3 23]
 [ 2  1 33]
 [31  3 23]]


array([[ 4,  3, 35],
       [33,  5, 25],
       [ 4,  3, 35],
       [33,  5, 25]])

In [48]:
subtract = np.subtract(concat_row,1)
subtract

array([[ 1,  0, 32],
       [30,  2, 22],
       [ 1,  0, 32],
       [30,  2, 22]])

In [49]:
multiply = np.multiply(concat_row,2)
multiply

array([[ 4,  2, 66],
       [62,  6, 46],
       [ 4,  2, 66],
       [62,  6, 46]])

In [50]:
divide = np.divide(concat_row,2)
divide

array([[ 1. ,  0.5, 16.5],
       [15.5,  1.5, 11.5],
       [ 1. ,  0.5, 16.5],
       [15.5,  1.5, 11.5]])

In [51]:
# Raise each element to that particular power. 
power = np.power(concat_row,2)
power

array([[   4,    1, 1089],
       [ 961,    9,  529],
       [   4,    1, 1089],
       [ 961,    9,  529]], dtype=int32)

### Vector math

In [52]:
# Returns true if all elements in the array are same and equal
vector  = np.array_equal(array1,array2)
vector

False

In [53]:
np.sqrt(array1)

array([[1.41421356, 1.        , 5.74456265],
       [5.56776436, 1.73205081, 4.79583152]])

In [54]:
print(array1)
bitwise = ~array1
absolute = np.abs(bitwise)
print(absolute)


[[ 2  1 33]
 [31  3 23]]
[[ 3  2 34]
 [32  4 24]]


In [55]:
array3 = np.array([3.3,2.3,3.6,4.5])
np.ceil(array3)

array([4., 3., 4., 5.])

In [56]:
np.floor(array3)

array([3., 2., 3., 4.])

In [57]:
np.round(array3)

array([3., 2., 4., 4.])

In [58]:
np.log(array3)

array([1.19392247, 0.83290912, 1.28093385, 1.5040774 ])

In [59]:
np.sin(array3)

array([-0.15774569,  0.74570521, -0.44252044, -0.97753012])

In [60]:
np.mean(array3)

3.425

In [61]:
# Returns the sum of the array
array3.sum()

13.7

In [62]:
# Returns the minimum of the array
array3.min()

2.3

In [63]:
#Returns the maximum of the array
array3.max()

4.5

In [64]:
np.var(array3)

0.6168750000000001

In [65]:
# retuns maximum value of the specific axis
array_axis = np.array([(2,3,24),(5,16,7)])
np.max(array_axis,axis = 1)

array([24, 16])

In [66]:
np.var(array_axis)

62.916666666666664

In [67]:
np.std(array_axis, axis = 1)

array([10.14341604,  4.78423336])

In [68]:
# returns the correlation coefficient of the given array
print(array1)
print(array2)
np.corrcoef(array1,array2)

[[ 2  1 33]
 [31  3 23]]
[[ 3 23  8]
 [34  3  7]]


array([[ 1.        ,  0.26677945, -0.30364966, -0.36834142],
       [ 0.26677945,  1.        , -0.99926008,  0.79773046],
       [-0.30364966, -0.99926008,  1.        , -0.77394735],
       [-0.36834142,  0.79773046, -0.77394735,  1.        ]])